name: Magisk Manager APK Patcher
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: "Magisk version"
        required: true
        default: "canary"
        type: choice
        options:
        - stable
        - beta
        - canary
      url:
        description: 'URL (blank for selected branch)'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          architecture: x64
      
      - name: Setup Environment
        id: setup_environment
        run: |
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
          wget -O apktool.jar https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.6.1.jar
          chmod +x apktool
      
      - name: Setup mmpatch
        id: setup_mmpatch
        run: git clone https://github.com/Magisk-Modules-Alt-Repo/mmpatch

      - name: Identify Target Tag
        shell: python
        id: identify_target_tag
        run: |
          import urllib.request
          import os
          import json
          import requests
          
          branch = """${{ github.event.inputs.branch }}"""
          url = """${{ github.event.inputs.url }}"""
          
          if not branch:
              branch = "stable"
          if branch == "stable" or branch == "beta" or branch == "canary":
              ver = branch+json.loads(requests.get(f"https://github.com/topjohnwu/magisk-files/raw/master/${{ github.event.inputs.branch }}.json").content)['magisk']['version']
          
          if not url:
              url = json.loads(requests.get(f"https://github.com/topjohnwu/magisk-files/raw/master/${{ github.event.inputs.branch }}.json").content)['magisk']['link']
          
          with open(os.environ['GITHUB_ENV'], 'a') as g:
              g.write(f'VERSION={ver}\n')
              g.write(f'URL={ver}\n')
        
      - name: Fetch APK
        id: fetch_apk
        run: wget -O ./mmpatch/MagiskManager.apk "${{ env.URL }}"
      
      - name: Patch APK
        id: patch_apk
        run: |
          export PATH="$PATH:`pwd`"
          cd mmpatch
          ./mmpatch Magisk-Modules-Alt-Repo

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: manager-alt-${{ env.VERSION }}
          release_name: Magisk Manager (Alt Patched) ${{ env.VERSION }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mmpatch/mmpatch-signed.apk
          asset_name: MagiskManager-Alt-Repo-${{ env.VERSION }}.apk
          asset_content_type: application/apk
